/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/Book.java
 * Module: Book
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Book {
    @NotNull
    @Size(min = 10, max = 13)
    private String isbn;

    @NotNull
    @Size(max = 100)
    private String title;

    @NotNull
    @Size(max = 50)
    private String author;

    @NotNull
    private Integer publicationYear;

    @NotNull
    private Boolean isAvailable;
    
    public Book(@NotNull @Size(min = 10, max = 13) String isbn, 
                @NotNull @Size(max = 100) String title, 
                @NotNull @Size(max = 50) String author, 
                @NotNull Integer year) {
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publicationYear = year;
        this.isAvailable = true;
    }
    
    @Override
    public String toString() {
        return "ISBN: " + isbn +
               "\nTitle: " + title +
               "\nAuthor: " + author +
               "\nYear: " + publicationYear +
               "\nAvailable: " + (isAvailable ? "Yes" : "No");
    }
}